name: Build Maven
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'
  push:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'

jobs:
  Maven:
    permissions:
      security-events: write
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_build.yml@master
    with:
      version: '0.0.0-SNAPSHOT'
      maven-opts: '-s ./.github/settings.xml'
    secrets: inherit

  Snapshot:
    if: github.event_name == 'push'
    needs: [Maven]
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_deploy.yml@master
    with:
      version: '3.0.0-SNAPSHOT'
      maven-opts: '-s ./.github/settings.xml '
      deploy-url-snapshot: https://maven.pkg.github.com/${{ github.repository }}
      sign: true
      sbom: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      DEPLOY_SERVER_USER_NAME: ${{ github.actor }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
