name: Build Maven
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'
  push:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'

jobs:
  Maven:
    permissions:
      security-events: write
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_build.yml@master
    with:
      jdk-version: 17
      version: '3.0.0-SNAPSHOT'
    secrets: inherit

  dependabot:
    runs-on: ubuntu-latest
    needs: [Maven]
    if: ${{ github.actor == 'dependabot[bot]' }}

    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
      - name: Approve a PR
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr review --approve "$PR_URL"
      - name: Approve % enable auto-merge for PR
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: |
          gh pr review --approve "$PR_URL"
