name: Build Maven
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'
  push:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'

jobs:
  Maven:
    if: false
    permissions:
      security-events: write
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_build.yml@master
    with:
      version: '0.0.0-SNAPSHOT'
      maven-opts: '-s ./.github/settings.xml'
    secrets: inherit

  Snapshot:
    if: github.event_name == 'push'
   # needs: [Maven]
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_deploy.yml@master
    with:
      version: '3.0.0-SNAPSHOT'
      maven-opts: '-s ./.github/settings.xml '
      deploy-url-snapshot: 'https://maven.pkg.github.com/tobias-schmitz/isyfact-standards'
    secrets:
      DEPLOY_SERVER_USER_NAME: ${{ github.actor }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.GITHUB_TOKEN }}