name: Dependencies
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4

  Review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Review dependencies
        uses: actions/dependency-review-action@v4
