name: DependaBot
on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

env:
  PR_URL: ${{github.event.pull_request.html_url}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          alert-lookup: true
      - name: Add a major label
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-major' }}
        run: gh pr edit "$PR_URL" --add-label "major"
      - name: Add a minor label
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: gh pr edit "$PR_URL" --add-label "minor"
      - name: Add a patch label
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr edit "$PR_URL" --add-label "patch"
      - name: Add security labels
        if: ${{ steps.metadata.outputs.alert-state == 'OPEN' }}
        run: |
          gh pr edit "$PR_URL" --add-label "security"
          gh pr edit "$PR_URL" --add-label "${{ steps.metadata.outputs.cvvss }}"
      - name: Approve a PR
        if: $(echo "0.9 <= ${{ steps.metadata.outputs.compatibility-score }} | bc) == 1
        run: gh pr review --approve "$PR_URL"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.alert-state == 'OPEN' }} && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
