name: Dependencies
on:
  pull_request:
    branches:
      - master
      - 'release/**'

jobs:
  Review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Review dependencies
        uses: actions/dependency-review-action@v4