name: Dependencies
on:
  workflow_dispatch:
    inputs:
      jdk-version:
        description: 'Version of jdk that is used.'
        required: false
        type: number
        default: 17
  workflow_call:
    inputs:
      jdk-version:
        description: 'Version of jdk that is used.'
        required: false
        type: number
        default: 17

env:
  JDK_VERSION: ${{ inputs.jdk-version || 17 }}

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK_VERSION }}
        if: github.event_name == 'push'
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: temurin
          cache: maven
      - name: Update dependency graph
        if: github.event_name == 'push'
        uses: advanced-security/maven-dependency-submission-action@v3.0.2
      - name: 'Dependency Review'
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v3
