name: Dependencies
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3.0.2

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2