name: Build Documentation
on:
  pull_request:
    branches:
      - master
    paths:
      - 'isyfact-standards-doc'
  push:
    branches:
      - master
env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build Documentation
        continue-on-error: true
        working-directory: isyfact-standards-doc
        run: mvn compile $MAVEN_CLI_OPTS -Dcheckstyle.skip -pl isy-documentation
  Test:
    runs-on: ubuntu-latest
    steps:
      - echo "Nothing to test"