name: Check Licenses
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@main
        with:
          fail-on: 'violations'
          report-formats: 'WebApp,PdfTemplate'
          run: >
            cache-dependencies,
            metadata-labels,
            analyzer,
            evaluator,
            reporter,
            upload-results

  rat:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - run: mvn $MAVEN_CLI_OPTS apache-rat:check
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          path: '**/rat.txt'