name: Build Maven
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'
  push:
    branches:
      - master
env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'
jobs:
  Maven:
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template-maven.yml@master