name: Release Maven
on:
  release:
    types: [released]

jobs:
  Build:
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_build.yml@master
    with:
      version: ${{ github.ref_name }}
      jdk-version: 8
      sonar-skip: true

  QualityGate:
    runs-on: ubuntu-latest
    needs: [Build]
    env:
      COMMIT_SHA: ${{ github.sha }}
      BRANCH_REF: release/2.x
      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
    steps:
      - name: SonarQube Quality Gate Check
        run: |
          ANALYSIS_ID=$( curl --silent "${SONAR_HOST_URL}/api/project_analyses/search?project=${SONAR_PROJECT_KEY}&branch=${BRANCH_REF/\//%2F}" | jq ".analyses[]|select(.revision==\"$COMMIT_SHA\").key" | tr -d \")
          
          if [[ -z $ANALYSIS_ID ]]; then
            echo "No Sonar Scan result found for commit $COMMIT_SHA"
            exit 1
          fi
          
          QG_STATUS=$(curl --silent "${SONAR_HOST_URL}/api/qualitygates/project_status?analysisId=${ANALYSIS_ID}" | jq ".projectStatus.status" | tr -d \")
          
          if [[ $QG_STATUS == "OK" ]]; then
            echo "Quality Gate passed"
            exit 0
          elif [[ $QG_STATUS == "ERROR" ]]; then
            echo "Quality Gate failed"
            exit 1
          else
            echo "Could not find Quality Gate information for analysis id ${ANALYSIS_ID}"
            exit 1
          fi

  Deploy:
    needs: [QualityGate]
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_deploy.yml@master
    with:
      version: ${{ github.ref_name }}
      jdk-version: 8
    secrets:
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      MAVEN_CENTRAL_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
      MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
