name: Check Maven
on:
  pull_request:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - 'isyfact-standards-doc'
  push:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - 'isyfact-standards-doc'

jobs:
  Version:
    uses: tobias-schmitz/isyfact-standards/.github/workflows/next_version.yml@master

  Maven:
    needs: [Version]
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_build.yml@master
    with:
      version: ${{ needs.Version.outputs.next-version }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}