name: Build Maven
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'
  push:
    branches:
      - master
    paths-ignore:
      - 'isyfact-standards-doc'

jobs:
  Maven:
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven.yml@master
    with:
      jdk-version: 17
      version: '3.0.0-SNAPSHOT'
    secrets: inherit