name: Deploy Snapshot
on:
  workflow_run:
    workflows: ["Build Maven"]
    types: [completed]
    branches: [master, 'release/*']

jobs:
  Snapshot:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - run: echo "Test"