name: Build Maven
on:
  pull_request:
    branches:
      - 'release/**'
    paths-ignore:
      - 'isyfact-standards-doc'
  push:
    branches:
      - 'release/**'

jobs:
  Maven:
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_build.yml@master
    with:
      jdk-version: 8
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Dependabot:
    runs-on: ubuntu-latest
    needs: [ Maven ]
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}

    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}

      steps:
        - name: Get Dependabot PR metadata
          id: metadata
          uses: dependabot/fetch-metadata@v1
          with:
            alert-lookup: true
            compat-lookup: true
            github-token: ${{ secrets.DEPENDABOT_TOKEN }}
        - name: Approve PR
          if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
          run: gh pr review --approve "$PR_URL"
        - name: Enable auto-merge for PR
          if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
          run: |
            gh pr review --approve "$PR_URL"
