name: Build Maven
on:
  pull_request:
    branches:
      - 'release/**'
    paths-ignore:
      - 'isyfact-standards-doc'
  push:
    branches:
      - 'release/**'

jobs:
  Maven:
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_build.yml@master
    with:
      jdk-version: 8
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
