name: Release Maven
on:
  release:
    types: [released]

jobs:
  Build:
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_build.yml@master
    with:
      version: ${{ github.ref_name }}
      jdk-version: 8
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  QualityGate:
    runs-on: ubuntu-latest
    needs: [Build]
    continue-on-error: true
    steps:
      - name: Download Sonar Scan Meta Data
        uses: actions/download-artifact@v3
        with:
          name: Sonar Meta Data
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        with:
          scanMetadataReportFile: report-task.txt
          timeout-minutes: 2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Deploy:
    needs: [Build]
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_deploy.yml@master
    with:
      version: ${{ github.ref_name }}
      jdk-version: 8
    secrets:
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      MAVEN_CENTRAL_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
      MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
