name: Release Maven
on:
  release:
    types: [released]
  workflow_call:

env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'

jobs:

  Build:
    permissions:
      security-events: write
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_build.yml@master
    with:
      jdk-version: 17
      version: ${{ github.ref_name }}
    secrets: inherit

  QualityGate:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download Sonar Scan Meta Data
        uses: actions/download-artifact@v3
        with:
          name: Sonar Meta Data
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        with:
          scanMetadataReportFile: report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: "SonarCloud Quality Gate Status"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

  Deploy:
    needs: [Build, QualityGate]
    uses: tobias-schmitz/isyfact-standards/.github/workflows/template_maven_deploy.yml@master
    with:
      version: ${{ github.ref_name }}
    secrets:
        MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_CENTRAL_USER_NAME: ''
        MAVEN_CENTRAL_TOKEN: ''