name: CVE Report
on:
  push:

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Cache CVE
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data/9.0/**
          key: ${{ runner.os }}-nvd
          restore-keys: ${{ runner.os }}-nvd
          save-always: true
      - name: Generate report
        working-directory: isyfact-products-bom
        run: mvn -DskipDependencyManagement=false $MAVEN_CLI_OPTS compile org.owasp:dependency-check-maven:9.0.9:check
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: CVE Report
          path: ${{ github.workspace }}/**/target/dependency-check-report.html