name: Build Maven Template
on:
  workflow_call:
    inputs:
      jdk-version:
        description: 'Version of jdk that is used.'
        required: false
        type: number
        default: 17
      maven-opts:
        description: 'Additional arguments passed to maven'
        required: false
        type: string
        default: ''
      checkout-lfs:
        description: 'Checkout files from Git LFS'
        required: false
        type: boolean
        default: false
      version:
        description: 'Version used for maven CI friendly versions'
        required: false
        type: string
        default: '0.0.0-SNAPSHOT'
      sonar-skip:
        description: 'Skip Sonar Scan job'
        required: false
        type: boolean
        default: false
      environment:
        description: 'GitHub Actions Environment'
        required: false
        type: string
        default: ''
    secrets:
      SONAR_TOKEN:
        description: 'Token to publish analysis result on sonar'
        required: false
      GH_PACKAGE_TOKEN:
        description: 'Token for github packages'
        required: false

env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'
  PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}

jobs:
  Compile:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.checkout-lfs }}
      - name: Set up JDK ${{ inputs.jdk-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.jdk-version }}
          distribution: temurin
          cache: maven
      - name: Compile
        run: mvn $MAVEN_CLI_OPTS ${{ inputs.maven-opts }} -Drevision=${{ inputs.version }} -Dcheckstyle.skip compile

  Test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [Compile]
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.checkout-lfs }}
      - name: Set up JDK ${{ inputs.jdk-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.jdk-version }}
          distribution: temurin
          cache: maven
      - name: Run tests
        run: mvn $MAVEN_CLI_OPTS ${{ inputs.maven-opts }} -Drevision=${{ inputs.version }} -Dcheckstyle.skip test
      - name: Create summary
        run: |
          echo "| Module | Total Coverage |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          COUNTER=0
          SUM=0
          for REPORT in $(find . -path \*target/site/jacoco/index.html); do
            MODULE=$(grep -o '<title>[^%].*</title>'  "$REPORT"| sed 's/<\/\?title>//g')
            COVERAGE=$(grep -o 'Total[^%]*%' "$REPORT" | sed 's/<.*>/ /; s/Total//; s/ //; s/%//')
            echo "| $MODULE | $COVERAGE % |" >> $GITHUB_STEP_SUMMARY
            COUNTER=$((COUNTER+1))
            SUM=$((SUM+COVERAGE))
          done
          [[ $COUNTER -gt 0 ]] && TOTAL_COVERAGE=$((SUM/COUNTER)) || TOTAL_COVERAGE=0
          echo "| Overall | $TOTAL_COVERAGE % |" >> $GITHUB_STEP_SUMMARY
      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: |
            ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
            ${{ github.workspace }}/**/target/surefire-reports/*.xml

  SonarScan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    # run also, if test or code quality jobs fail; skip dependabot pr as dependabot has separate secrets
    if: vars.SONAR_PROJECT_KEY && !cancelled() && github.actor != 'dependabot[bot]' && !inputs.sonar-skip
    needs: [Test]
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.checkout-lfs }}
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Set up JDK 17
        # Sonar Plugin requires Java 17 or higher
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Cache Sonar
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Download Test Reports
        uses: actions/download-artifact@v3
        with:
          name: Test Reports
      - name: Sonar Scan
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          mvn $MAVEN_CLI_OPTS ${{ inputs.maven-opts }} -Drevision=${{ inputs.version }}
          -DskipTests -Dspotbugs.skip -Dcheckstyle.skip -Dmaven.javadoc.skip -Denforcer.skip
          -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
          -Dsonar.qualitygate.wait=true
          verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar
      - name: Upload Meta Data
        uses: actions/upload-artifact@v3
        with:
          name: Sonar Meta Data
          path:
            ${{ github.workspace }}/target/sonar/report-task.txt
