name: Build Maven
on:
  workflow_call:
    inputs:
      jdk-version:
        description: 'Version of jdk that is used.'
        required: false
        type: number
        default: 17
      maven-opts:
        description: 'Additional arguments passed to maven'
        required: false
        type: string
        default: ''
      checkout-lfs:
        description: 'Checkout files from Git LFS'
        required: false
        type: boolean
        default: false
      version:
        description: 'Version used for maven CI friendly versions'
        required: false
        type: string

env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: ${{ inputs.checkout-lfs }}
      - name: Set up JDK ${{ inputs.jdk-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.jdk-version }}
          distribution: temurin
          cache: maven
      - name: Compile
        run: mvn $MAVEN_CLI_OPTS ${{ inputs.maven-opts }} -Drevision=${{ inputs.version }} -Dcheckstyle.skip compile
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Target Folder
          path: ${{ github.workspace }}/**/target/

  Test:
    runs-on: ubuntu-latest
    needs: [Compile]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: ${{ inputs.checkout-lfs }}
      - name: Set up JDK ${{ inputs.jdk-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.jdk-version }}
          distribution: temurin
          cache: maven
      - name: Test
        run: mvn $MAVEN_CLI_OPTS ${{ inputs.maven-opts }} -Drevision=${{ inputs.version }} -Dcheckstyle.skip test
      - name: Create Summary
        run: |
          echo "| Module | Total Coverage |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          COUNTER=0
          SUM=0
          for REPORT in $(find . -path \*target/site/jacoco/index.html); do
            MODULE=$(grep -o '<title>[^%].*</title>'  "$REPORT"| sed 's/<\/\?title>//g')
            COVERAGE=$(grep -o 'Total[^%]*%' "$REPORT" | sed 's/<.*>/ /; s/Total//; s/ //; s/%//')
            echo "| $MODULE | $COVERAGE % |" >> $GITHUB_STEP_SUMMARY
            COUNTER=$((COUNTER+1))
            SUM=$((SUM+COVERAGE))
          done
          [[ $COUNTER -gt 0 ]] && TOTAL_COVERAGE=$((SUM/COUNTER)) || TOTAL_COVERAGE=0
          echo "| Overall | $TOTAL_COVERAGE % |" >> $GITHUB_STEP_SUMMARY
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: |
            ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
            ${{ github.workspace }}/**/target/surefire-reports/*.xml

  CodeQuality:
    runs-on: ubuntu-latest
    needs: [Compile]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: ${{ inputs.checkout-lfs }}
      - name: Set up JDK ${{ inputs.jdk-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.jdk-version }}
          distribution: temurin
          cache: maven
      - name: Checkstyle
        run: >
          mvn $MAVEN_CLI_OPTS ${{ inputs.maven-opts }} -Drevision=${{ inputs.version }} 
          compile checkstyle:checkstyle-aggregate
      - name: Spotbugs
        run: >
          mvn $MAVEN_CLI_OPTS ${{ inputs.maven-opts }} -Drevision=$${{ inputs.version }} 
          -Dcheckstyle.skip -Denforcer.skip -Dtidy.skip compile spotbugs:check

  SonarScan:
    runs-on: ubuntu-latest
    # run also , if test job fails
    if: ${{ !cancelled() }}
    needs: [Test]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: ${{ inputs.checkout-lfs }}
      - name: Set up JDK 17
        # Sonar Plugin requires Java 17 or higher
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Download Test Reports
        uses: actions/download-artifact@v3
        with:
          name: Test Reports
      - name: Sonar Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn $MAVEN_CLI_OPTS ${{ inputs.maven-opts }} -Drevision=${{ inputs.version }}
          -DskipTests -Dspotbugs.skip -Dcheckstyle.skip -Dmaven.javadoc.skip
          -Dsonar.organization=ts-test -Dsonar.projectKey=tobias-schmitz_isyfact-standards 
          -Dsonar.host.url=https://sonarcloud.io 
          verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar