name: Deploy Maven Template
on:
  workflow_call:
    inputs:
      version:
        description: 'Version used for maven CI friendly versions'
        required: true
        type: string
    secrets:
      MAVEN_GPG_PRIVATE_KEY:
        required: true
        description: 'Private GPG key to sign artifacts with'
      MAVEN_GPG_PASSPHRASE:
        required: true
        description: 'Passphrase for private gpg key'
      MAVEN_CENTRAL_USER_NAME:
        required: true
        description: 'User name for maven central for deployment'
      MAVEN_CENTRAL_TOKEN:
        required: true
        description: 'Token for maven central deployment'

env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'

jobs:
  Validate:
    runs-on: ubuntu-latest
    # environment: Release
    steps:
      - name: Validate tagged version
        run: |
          RE_SEMVER="^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$"
        
          if [[ ! "${{ inputs.version }}" =~ $RE_SEMVER ]]; then
            echo "ERROR tag with value ${{ inputs.version }} is an invalid release or semantic version"
            echo "Release requires a current tag containing a valid SemVer 2.0.0. without pre-release version"
            exit 1
          fi
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
      - name: Validate project version
        run: |
          PROJECT_VERSION=$(mvn -Dexpression=project.version -q -DforceStdout -Drevision=${{ inputs.version }} help:evaluate)
          if [ ! "$PROJECT_VERSION" = "${{ inputs.version }}" ]; then
            echo "ERROR tag with value ${{ inputs.version }} does not correspond to project version $PROJECT_VERSION"
            exit 1
          fi
      - name: Check release existence
        continue-on-error: true
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        run: >
          mvn $MAVEN_CLI_OPTS $MAVEN_OPTS
          -Dexists.failIfExists=true
          -Dexists.skipIfSnapshot=true
          -Dexists.serverId=ossrh
          -Dexists.snapshotServerId=ossrh
          -Drevision=${{ inputs.version }}
          -Dcentraldeploy=true
          org.honton.chas:exists-maven-plugin:0.7.0:remote

  Deploy:
    runs-on: ubuntu-latest
    # environment: Release
    needs: [Validate]
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          # arguments for generated settings.xml, see https://github.com/actions/setup-java/blob/v3.11.0/docs/advanced-usage.md#publishing-using-apache-maven
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy

      - name: Package, Sign & Deploy
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        run: >
          mvn -DskipTests -Dspotbugs.skip -Dcheckstyle.skip  -DdeployAtEnd -Drevision=${{ inputs.version }}
          $MAVEN_CLI_OPTS -P GPGsigning cyclonedx:makeBom deploy
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: |
            /tmp/deploy/test/